name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      run: sudo apt-get install python3 -y

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run application
      run: python app.py
      